### ISSUE TITLE
"gl_overbright_models 0" is brighter instead of darker

### ISSUE THREAD

**Issue by d-bind** [andrei-drexler/ironwail#80]
By default overbright models are on, and don't differ from Quakespasm with overbrighting.
But turning them off makes the models even brighter (the effect increases the brighter the lighting).
Possibly a deprecated cvar? (as it seems like the shader just always overbrights regardless)

**Comment by garoto** [comment]
Can confirm I guess. Noticed this when I ported my QSS config to Ironwail. Took me a while to figure out what CVAR was the culprit.

**Comment by andrei-drexler** [comment]
Thanks! Fixed in a389fa3415659fdb77f98fb4d1230abb7537b726.

**Comment by andrei-drexler** [comment]
Looks like there are still some cases when this isn't quite right, I'll have to take a closer look.

**Comment by d-bind** [comment]
Right, it is still brighter near the brightest spot.
Here's a test map (run with -quoth) and some comparison shots in case you want to match the original renderer closer.
[overbr_m.zip](https://github.com/andrei-drexler/ironwail/files/8570291/overbr_m.zip)

**Comment by d-bind** [comment]
Sorry, nope, still not quite.
Now with overbrighting on, the fullbright pixels get blown out.

Also, arguably a bug: clamping the light values prevents models in bright areas from being affected by dynamic lights, unlike bsp geometry. Same in QS.

**Comment by andrei-drexler** [comment]
Fixed the blown out fullbrights in 5857f3f.

**Comment by d-bind** [comment]
Yes, now it's good.

**Comment by andrei-drexler** [comment]
Alright, thanks for testing this and letting me know.

Re: clamping - unfortunately it's necessary to match QS, otherwise there would still be situations where `gl_overbright_models 0` would be brighter than `1` (e.g. the viewmodel when standing in the AD start map at `(-287 -341 360) 6 30 0`). For the time being I'm content with just matching QS, even if it's not ideal. The code is rather finicky IMO, and I'd rather spend my time addressing more pressing issues. I might revisit this in the future, though, if I don't run out of steam until then.
